#ifndef BONGO_CAT_UI_ICONS_H
#define BONGO_CAT_UI_ICONS_H

typedef enum BongoCatUIIcon {
    BONGO_CAT_UI_ICON_CAT,
    BONGO_CAT_UI_ICON_SETTINGS,
    BONGO_CAT_UI_ICON_WAND,
    BONGO_CAT_UI_ICON_KEYBOARD,
    BONGO_CAT_UI_ICON_HEART,
    BONGO_CAT_UI_ICON_GITHUB,
    BONGO_CAT_UI_ICON_DISCORD,
    BONGO_CAT_UI_ICON_QQ,
    BONGO_CAT_UI_ICON_COFFEE,
    BONGO_CAT_UI_ICON_UPLOAD,
    BONGO_CAT_UI_ICON_CHECK,
    BONGO_CAT_UI_ICON_VERIFIED,
    BONGO_CAT_UI_ICON_SMILE,
    BONGO_CAT_UI_ICON_FOLDER,
    BONGO_CAT_UI_ICON_TRASH,
    BONGO_CAT_UI_ICON_CIRCLE_X,
    BONGO_CAT_UI_ICON_PLAY,
    BONGO_CAT_UI_ICON_SYNC,
    BONGO_CAT_UI_ICON_CLOSE,
    BONGO_CAT_UI_ICON_COUNT
} BongoCatUIIcon;

#endif
